//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convert.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("convert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///&lt;h1 id=&quot;h1-heading-1&quot;&gt;&lt;a name=&quot;Heading 1&quot; class=&quot;reference-link&quot;&gt;&lt;/a&gt;&lt;span class=&quot;header-link octicon octicon-link&quot;&gt;&lt;/span&gt;Heading 1&lt;/h1&gt;
        ///&lt;p&gt;&lt;em&gt;斜体字&lt;/em&gt;
        ///    &lt;em&gt;斜体字&lt;/em&gt;
        ///    &lt;strong&gt;粗体&lt;/strong&gt; 
        ///    &lt;strong&gt;粗体&lt;/strong&gt;
        ///    &lt;strong&gt;&lt;em&gt;粗斜体&lt;/em&gt;&lt;/strong&gt; 
        ///    &lt;strong&gt;&lt;em&gt;粗斜体&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;
        ///&lt;pre&gt;
        ///    &lt;code class=&quot;lang-javascript&quot;&gt;function test() {
        ///          console.log(&quot;Hello world!&quot;);
        ///      }
        ///    &lt;/code&gt;
        ///&lt;/pre&gt;
        ///&lt;h3 id=&quot;h3--images&quot;&gt;&lt;a name=&quot;图片 Images&quot; class=&quot;reference-link&quot;&gt;&lt;/a&gt;&lt;span c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemoHtml {
            get {
                return ResourceManager.GetString("DemoHtml", resourceCulture);
            }
        }
    }
}
